# SPDX-FileCopyrightText: 2026 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddWebauthnSecondFactorResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webauthn_second_factor_credentials, primary_key: false) do
      add(:last_used_at, :utc_datetime_usec)
      add(:label, :text, default: "Security Key")
      add(:discoverable, :boolean)
      add(:backed_up, :boolean)
      add(:backup_eligible, :boolean)
      add(:transports, {:array, :text})
      add(:user_handle, :binary)
      add(:sign_count, :bigint, null: false, default: 0)
      add(:public_key, :binary, null: false)
      add(:credential_id, :binary, null: false)
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:user_id, :uuid, null: false)
    end

    create unique_index(:webauthn_second_factor_credentials, [:credential_id],
             name: "webauthn_second_factor_credentials_unique_credential_id_index"
           )

    create table(:user_with_webauthn_second_factor, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:webauthn_second_factor_credentials) do
      modify(
        :user_id,
        references(:user_with_webauthn_second_factor,
          column: :id,
          name: "webauthn_second_factor_credentials_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:user_with_webauthn_second_factor) do
      add(:email, :citext, null: false)
      add(:hashed_password, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:user_with_webauthn_second_factor, [:email],
             name: "user_with_webauthn_second_factor_unique_email_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:user_with_webauthn_second_factor, [:email],
        name: "user_with_webauthn_second_factor_unique_email_index"
      )
    )

    alter table(:user_with_webauthn_second_factor) do
      remove(:updated_at)
      remove(:created_at)
      remove(:hashed_password)
      remove(:email)
    end

    drop(
      constraint(
        :webauthn_second_factor_credentials,
        "webauthn_second_factor_credentials_user_id_fkey"
      )
    )

    alter table(:webauthn_second_factor_credentials) do
      modify(:user_id, :uuid)
    end

    drop(table(:user_with_webauthn_second_factor))

    drop_if_exists(
      unique_index(:webauthn_second_factor_credentials, [:credential_id],
        name: "webauthn_second_factor_credentials_unique_credential_id_index"
      )
    )

    drop(table(:webauthn_second_factor_credentials))
  end
end
