defmodule Example.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_with_web_authn, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:email, :citext, null: false)
    end

    create unique_index(:user_with_web_authn, [:email], name: "user_with_web_authn_email_index")

    create table(:user_webauthn_keys, primary_key: false) do
      add(:last_used_at, :utc_datetime_usec)
      add(:transports, {:array, :text})
      add(:aaguid, :binary)
      add(:sign_count, :bigint, null: false, default: 0)
      add(:public_key, :binary, null: false)
      add(:credential_id, :binary, null: false)
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)

      add(
        :user_id,
        references(:user_with_web_authn,
          column: :id,
          name: "user_webauthn_keys_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create unique_index(:user_webauthn_keys, [:credential_id],
             name: "user_webauthn_keys_unique_credential_id_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:user_webauthn_keys, [:credential_id],
        name: "user_webauthn_keys_unique_credential_id_index"
      )
    )

    drop(constraint(:user_webauthn_keys, "user_webauthn_keys_user_id_fkey"))

    drop(table(:user_webauthn_keys))

    drop_if_exists(
      unique_index(:user_with_web_authn, [:email], name: "user_with_web_authn_email_index")
    )

    drop(table(:user_with_web_authn))
  end
end
