defmodule Example.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_with_web_authn) do
      modify(:email, :citext, null: true)
    end

    alter table(:user_webauthn_keys) do
      modify(:user_id, :uuid, null: false)
    end
  end

  def down do
    alter table(:user_webauthn_keys) do
      modify(:user_id, :uuid, null: true)
    end

    alter table(:user_with_web_authn) do
      modify(:email, :citext, null: false)
    end
  end
end
